#+TITLE: Sammy's Blog
#+HTML_HEAD: <style> body {width:80%; margin-left: 10%;}</style>
* Treating Cancer with Chemo (Part 3)
  In this section, we now look at the specific drugs we would need to put the ideas in Part 2 into practice. We have a tremendous advantage here because we are not developing new chemicals. All of the drugs listed have already seen clinical use.
  What we'd like to do is, send a signal that tells all the cells in your body to start dividing, and then send a chemotherapy drug which kills any cells that are still dividing. Your body has many types of signals which tell cells when to grow and divide, 

notes:
platelts come from Megakaryocytes which come from  hematopoietic stem cells

I found the paper that has this idea https://www.ncbi.nlm.nih.gov/pubmed/8839398
  
  
* Treating Cancer with Chemo (Part 2)
  In the last section we looked into what types of cancer treatments are out there, and, from a research perspective, what areas hopefully have the most low hanging fruit. Due to cancer heterogeneity, and the problem of targeting undetectable or microscopic tumors, black-box chemotherapy methods seemed like they would yield the best results. I wrote down the definition of our "black box" and narrowed in on one property, that cancer cells divide regardless of external signaling.

  Many drugs already target this pathway. Certain drugs attack cells which divide more rapidly, intentionally causing damage to cells during the process of cell division. In theory this will cause cancer cells to die because they will be more likely to die than the normal cells.

  The problem is, this also kills healthy cells. Some cells, such as bone marrow cells, divide rapidly and, some cancers don't even grow that quickly. Some cancers grow at a normal rate for cells, they just don't stop growing when they're supposed to. The problem is that what you want to measure is not the cancer's rate of growth, but it's responsiveness to external signals within the body.

  So how can we target this? How do we identify cells which don't respond to signals?

  Well, instead of targeting cancer cells, we can send signals to identify healthy cells. We know that the healthy cells will respond to the signals and the cancer cells won't. By targeting everything else, we can measure when something doesn't respond to the signals that it's supposed to, and then go after it. Instead of attacking cells that divide quickly, we can tell all of the cells to stop dividing, and then kill all the cells that still divide. The cancer cells won't listen, but the normal cells will, so they won't get the damage that usually comes with intensive chemotherapy.

  What's completely wild about this to me is that people are doing this already, but not on the cells that actually matter. We treat hair loss. We can help people not lose all their hair who are going through chemo by having them apply ice packs to the top of their head while they're receiving treatment. This works by slowing the division of the cells around your hair follicles, so they won't actually get killed and fall out while you're getting treatment.

  In the same way that we treat hair loss, we can tell the cells in your bone marrow to stop dividing as quickly while the chemo is active and thus drastically reduce the side effects. Furthermore, we'd be able to use drugs that weren't previously available because even though they killed the cancer they were otherwise too toxic to the human body. Even better, we already have the tools to do this. We already have drugs which slow the growth of bone marrow cells. We just have to apply them in the right way.

* Treating Cancer with Chemo (Part 1)
  Cancer treatment is something I've thought about a lot recently, and the more I've studied it, the more I've seen that it's an interesting and complex problem. At it's core a cancer is a group of cells whose genetic code has mutated such that they divide uncontrollably, in a way that cannot be properly regulated by the body. Cancer cells, in contrast to benign tumors, also have the ability to sustain their growth, and to invade other parts of the body. If the cancer cells grow too much, they can "crowd out" other bodily functions, by having large tumors that press against vital organs, or "replace" other healthy cells.

  The challenge with treatment is that cancer cells, unlike bacteria or viruses, look remarkably like healthy human cells. It's difficult to kill the cancer cells without accidentally killing the normal cells. As a result, the main treatment options for cancer are:
  - Surgery: Cancers typically grow as a cluster of cells in the same physical location, called a tumor. One way to treat this is to just cut out the tumor. This is good because it can quickly and fully remove the entire tumor, but bad because it might not be in a place you can safely reach with a knife, and bad because it doesn't catch it if the cancer spread without your knowledge.
  - Radiation: Radiation zaps the cancer with high intensity beams of light. Think a really powerful microwave pointed directly at your tumor. This is good because it kills cells in places that aren't easy to reach with a knife, and can cover a wider area than would be safe to cut out, but bad because it might not kill everything in its beam and again, it won't catch the cancer if it spreads.
  - Chemotherapy: This is a broad term that refers to using chemicals to kill, or otherwise harm the cancer cells. Since this refers to many different types of chemicals, which act in many different types of ways, it's hard to give a one-size-fits all explanation. One type of chemical which is fairly common essentially tries to kill cells which are dividing very quickly or haphazardly, hoping to target the cancer cells unctonrollable growth. Chemotherapy is great because unlike radiation or surgery, it can attack cancer cells anywhere in the body, meaning that if the tumor had spread to a small undetectable cluster of cells, chemotherapy would still fight it. The downside of chemotherapy is it's not always very good at determining which cells are cancer cells. This means it can kill healthy cells all over your body, most notably in the bone marrow, which tends to replenish quickly.

  There are a few other types of treatments, such as immunotherapy, which I'll skip for now as largely niche (but growing) fields.


  I'd like to focus here on chemotherapy because, while currently surgery and radiation are often necessary, because they are unable to attack small groups of cells, I don't believe that in the future, anything more than incremental progress will be made. Whatever the solution is will likely have to be some sort of medicine because we can't physically target something we don't have the ability to detect.

  Medicines that treat cancer (even including immunotherapy) are hard to make because it's hard for anything to classify whether or not a cell is cancerous. So, in order to treat cancer, we need to solve the classification problem, build a model to predict whether or not a cell is cancerous, and then encode it on a macroscopic scale. The more accurate our model, the more likely that the drug will kill the cancer without being otherwise fatal to the human body.

  We can approach this classification as a "black box", i.e. the cell is a generic thing with certain properties which we can't see into. Or, we can think of it as an open box, i.e. the mutated DNA of a cancer cell causes these specific chemical reactions which, eventually cause the cell to divide uncontrollably. With open box models, we have a tremendous amount more information that we can use to classify the cell as dangerous, and it seems like this would be intrinsically easier, but this information comes at a cost. Cancer is a name for a disease that can occur in many different ways and for many different reasons, often exhibiting significant heterogeneity within a single tumor. If we treat one specific pathway of chemical reactions, we'll only solve the problem for those specific cells, and we'll miss out on all the different types of cancer that are possible.

  I'd like to think about this problem as a black box problem because in addition to the curse of heterogeneity, it's also just better suited to my background. Treating the cell as an open box generally means lab work with equipment I don't have access to, and at best a 5-10 year trial period before a new chemical gets into production. It's my hypothesis that there are enough building blocks that are already well studied, that if we put them together in just the right way, we'll get a better result.

  So let's take a look at the black box. I took a look at the definition of a cancer cell. It boils down to roughly:
  1. The cells grow and divide regardless of what body signals them to do
  2. They don't die when they're supposed to
  3. They can invade other parts of the body
  4. They get the rest of the body to support their growth (encourage blood vessel construction)

  I'd say 2 is almost impossible to go after as a black box, since you can't ask a cell whether it will die without killing it. 3 seems similarly difficult because at best it can only attack spread, and not the original tumor, and because it's hard to ask a cell where it originally came from. 4 seems promising, but again has the problem that it likely won't cure tumors of smaller than a certain size. So, all things considered, I'd like to take a closer look at 1, that cancer cells grow and divide regardless of the body's signals.
    
* The Importance of Doing Nothing
  This morning I woke up, a little on the later side, and didn't have anything important to do. I didn't have work, and I didn't have chores, just had to eat breakfast, and be out the door by noon. I had 2 and a half hours, so it should have been easy.

  With so much time, and nothing, really, to do, I started browsing the front page of reddit. I thought maybe the act of reading, or looking at something would wake me up a little. 30 minutes passed. This was no big deal, as I had all morning, really, but I felt like I wasn't quite done yet, so I kept going.

  By 1130, I was still searching for something initeresting, and I still hadn't found what I was looking for. I knew I was wasting time, and I knew that I wasn't going to feel fully satisfied at the end of it, but it always felt like the next two or three minutes would make me feel a little bit better, and that little time wouldn't be a deal breaker. By the end of it, I would click on a YouTube video and only watch the last thirty seconds of it, because in truth I didn't really want to watch the video, but I wanted to feel like I was going to find something new and entertaining. I didn't really feel like I was thinking at all, or even that I was enjoying what I was doing, but I wanted to see something. You can probably guess that I rushed the quickest breakfast (read: two bananas), and was out the door 20 minutes late.

  Whenever I mess something up, I ask myself how I could of done better. In this case it seems pretty obvious. I could have just not wasted 3 hours scrolling around on the internet. I could have looked at Reddit for only an hour and a half, made myself a delicious breakfast, and still left on time.

  But in practice, it's not that simple. That's because what you do with your time affects your ability to think and make decisions. If, after 90 minutes, I took a break to really sit, and think clearly about what I wanted to be doing, I would have realized I still wanted to breakfast, and that I wanted to be on time. But because I was watching videos, and because I was constantly blasting my mind with different signals, I never had a moment to really process what was going on.

  Not only that, I noticed even after I left my apartment, after I had already stopped looking at a screen, I was still left with that same mentality. While I was walking to the train, I still felt this impulse to play chess or read the news. I wasn't thinking about the rest of the day, or about things I wanted to learn, or things I really cared about. For most of the afternoon, my head was still overloaded, and when I went to think, what came out were random memes and stories. I had given myself so much new information to process, that even after I was done looking at it, it still crowded out my other thoughts. It's not just about the moment, wasting your time does damage, and it's important to recognize what damage it's doing.

  Maybe the videos made me feel happy for a half hour or so. Maybe I even learned a tiny bit, about news, or life advice, or something that might make good conversation. But I think I would have been better off if I had done, really, absolutely nothing. I would have been better off if I just sat down in a chair, and just waited. When I do nothing, it gives me the mental space to process longer-term thoughts, to prepare for my day, and to figure out what I really, genuinely want to be doing.

* Why I Support Citizens United
  Most people I know really don't like Citizens United. For those who aren't familiar, Citizens United was a supreme court decision that essentially let corporations and wealthy individuals funnel unlimited amounts of money into American politics. Not only that, it let people donate to certain types of political causes with little to no transparency or oversight. The people I know who don't like it view it as letting big money buy elections and spread corruption in American politics.

  We have anti-bribery laws (which the courts have upheld). We have campaign finance laws (which the courts have upheld). So, what makes the Citizens United ruling different?

  The Citizens United ruling applies only to campaign advertisements (not general campaign contributions), and only to money that is spent "independently", i.e. without talking directly to the candidate or political party. This means that if I'm Exxon Mobile, I still can't write Mitch McConnell a check for 10 million dollars. I also can't work with Mitch McConnel to film a TV ad for his upcoming election. But if I decide that I really like Mitch McConnel, and I don't talk to anybody, and I just pay for an ad telling everyone how great he is, then nobody can stop me.

  As experience has shown, advertising can make a huge difference in the outcome of an election. If someone is allowed to spend an infinite amount of money on advertising, they, as an individual can have a massive influence on the outcome of an election. We have anti-bribery laws, but if someone can use money to ensure candidates with certain political views are elected, aren't the effects the same?

  I like to think of this by considering the role of a news organization. We need some news organizations discussing American politics in order to keep voters informed, so that they can better understand the issues and decide who to vote for. Along these lines, it's even important to have news organizations that debate different topics, and to have editorials which discuss their own opinions because it's important for people to understand the reasoning behind the legislation, and get a sense of why or why not something is a good idea. Especially for traditional media outlets like newspapers and television, It's nearly impossible to publish editorials or simply report the news without incurring some sort of bias.

  If you wanted to start a new cable news channel, you'd have to pay for a studio, for cable companies to distribute your broadcast, and to advertise your broadcast to others. Your news broadcast might be extremely biased, because, as we've already discussed, it's impossible to regulate bias in news organizations. You might not want a long-form news broadcast, so instead of paying for an entire television channel for an entire day, you might want to only purchase a slot that's the length of your show, or the message you want to publish. Separately, you might also want to be able to advertise your show (as news organizations are able to advertise), and in doing so accurately describe what's in it.

  So, the question is, where do you draw the line? What's the difference between paying to broadcast an editorial piece and donating directly to a political campaign? Well, I think making sure that the broadcast isn't part of (organized by) the political campaign itself is a pretty fair place to draw the line.
* Camera Settings
  When I got my first DSLR, I opened up the settings menu, and found it loaded with options: active-d lighting, vignette control, auto-bracketing, ambient lighting, and much more. It took a while to sift through all the options, but after assigning some reasonable defaults (use full resolution, turn on vibration reduction when available, etc.), I found that despite all of the options, there were really only four dials that effected the raw image. The rest were either only in post-processing, or just different ways of twisting those original four dials.

  Despite all the complexity, the only four dials you have on your camera are:
  1. Exposure

     Your camera has a sensor in it. When you take a picture, the camera opens up and lets light into the sensor. The longer the camera opens up, the more time light has to hit the sensor, and the brighter the overall image. 

     This comes from a time before people had digital cameras. When people used film, each wave of light would cause a chemical reaction on the film, so letting in waves of light for a longer period of time would cause more chemical reactions, and all of the individual waves of light would "add together" to form the overall image. That's why if you move a camera around while the film is exposed, the image comes out blurry.
  2. Focus Distance

     In front of the sensor, your camera has a lens. The job of the lens is to take in all of the light from the outside world, and bend it, so that the light is pointed at the sensor. Typically the outside world is larger than the size of the sensor, so the lens bends the light toward the center, with the light kind of following the shape of a cone. If the lens bends the light correctly, the square of the outside world that you want to capture will hit the image like a bunch of parallel beams of light, and you'll project a much bigger image onto a much smaller sensor. However, if the cone of light is too short, or too long, instead of hitting the image like parallel lines, the beams of light will get criss-crossed. Instead of one exact point on the outside world corresponding to one exact spot on the sensor, it might miss, and send some of the light kind of nearby, causing the image to be blurry. The correct focal distance is different for objects at different distances from the camera, so if you make nearby objects in focus, you make faraway objects out of focus.

     Long story short, if a part of an image is not in focus, it looks blurry. You get to choose a distance away from the camera such that objects at that distance are in focus. The further away an object is from the focus you chose, the more blurry it looks in the photo.
  3. Aperture

     Typically, there's a physical shutter that opens up when you take a picture to let light onto the film or sensor. Aperature refers to how big of an opening there is when the shutter is open. If there's a really big hole, it lets in a lot of light, but if there's really small hole, it only lets in a little bit of light. Also, if there's a small hole, the cone of light (from the focus section) is skinnier, so the beams don't get criss-crossed as much. This means that objects that aren't at the focus distance don't wind up being as blurry, because there's less interference. If there's a big hole, the cone is wider, so only objects at a specific distance are in focus, and everything else comes out blurry. This can be useful in taking portraits when you want to emphasize an in-focus person against an out-of-focus background.
  4. ISO

     How sensitive your camera sensors are to light. High ISO means your camera registers a lot of input from a small amount of light. Most cameras are only able to get accurate readings up to a certain level of sensitivity, so bumping your ISO too high can result in noisy/grainy images.


So why do cameras have so many other options? Well, taking photos in the real world it isn't always easy to quickly and accurately adjust these four dials to set up for the shot you want. Want to get that monkey in focus? The one that's swinging across the jungle? Good luck twisting your focus knob and trying to keep up with it. You'll probably want your camera's autofocus tracking. Want to take many photos in a row, with different levels of exposure? There's a setting for that. It's not enough to just have access to those dials, you also want convenience tools that let you quickly choose how and when to take a photo.

In addition, even though it doesn't effect the raw image, many cameras have built-in post-processing to adjust for things like ambient lighting. While for more serious shots, you'll probably edit the raw files in a program on your computer like photoshop or lightroom, it is convenient, visually to get quick feedback on what the image might look like, and for those of us that are lazy out there, can be a quick way to produce reasonable quality images.
